<?php

namespace Ohmangocat\GenBase\Util;



use support\Db;

class DbUtils extends Db
{
    public static function connection($connection = "plugin.ohmangocat.gen-base.mysql")
    {
        return parent::connection($connection); // TODO: Change the autogenerated stub
    }
}